### ISSUE TITLE
risk free scraping problem

### ISSUE THREAD

**Issue by tinix84** [Lienus10/yoptions#1]
d:\Miniconda3\envs\icm\lib\site-packages\yoptions\main.py in __risk_free(days)
    384 
    385     table = soup.find("table", attrs={'class': 't-chart'})
--> 386     rows = table.find_all('tr')
    387     lastrow = len(rows) - 1
    388     cells = rows[lastrow].find_all("td")

AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by dnkls** [comment]
Same problem 😕

**Comment by Lienus10** [comment]
The problem has been resolved in version 0.0.3
