### ISSUE TITLE
API no longer functional

### ISSUE THREAD

**Issue by jayurbain** [Lienus10/yoptions#2]
`
import yoptions as yo

# Chain of all FORD MOTOR COMPANY call options for next expiration date
chain = yo.get_chain_greeks(stock_ticker='F', dividend_yield=0, option_type='c', risk_free_rate=None)
print(chain.head().to_string())
`

AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 2>()
      1 # Chain of all FORD MOTOR COMPANY call options for next expiration date
----> 2 chain = yo.get_chain_greeks(stock_ticker='F', dividend_yield=0, option_type='c', risk_free_rate=None)
      3 print(chain.head().to_string())

File ~/opt/miniconda3/envs/pytorch_quant/lib/python3.9/site-packages/yoptions/main.py:19, in get_chain_greeks(stock_ticker, dividend_yield, option_type, risk_free_rate)
     16 with urllib.request.urlopen("https://query2.finance.yahoo.com/v7/finance/options/" + stock_ticker) as url:
     17     data = json.loads(url.read().decode())
---> 19 return __get_chain(option_type, data, dividend_yield, risk_free_rate)

File ~/opt/miniconda3/envs/pytorch_quant/lib/python3.9/site-packages/yoptions/main.py:245, in __get_chain(option_type, data, dividend_yield, r)
    243 if option_type == 'c':
    244     chain = data["optionChain"]["result"][0]["options"][0]["calls"]
--> 245     return __greeks(data, chain, option_type, r, dividend_yield)
    246 else:
    247     if option_type == 'p':

File ~/opt/miniconda3/envs/pytorch_quant/lib/python3.9/site-packages/yoptions/main.py:260, in __greeks(data, chain, option_type, r, dividend_yield)
    257 today = datetime.datetime.now()
    259 if r is None:
--> 260     r = __risk_free((expiration_date - today).days)
    262 contract_symbols = []
    263 last_traded = []

File ~/opt/miniconda3/envs/pytorch_quant/lib/python3.9/site-packages/yoptions/main.py:386, in __risk_free(days)
    383 soup = BeautifulSoup(r.text, 'html.parser')
    385 table = soup.find("table", attrs={'class': 't-chart'})
--> 386 rows = table.find_all('tr')
    387 lastrow = len(rows) - 1
    388 cells = rows[lastrow].find_all("td")

AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by Lienus10** [comment]
The problem has been resolved in version 0.0.3
